### ISSUE TITLE
Update information for Laravel MongoDB package

### ISSUE THREAD

**Issue by bisht2050** [HassanZahirnia/laravel-package-ocean#194]
For Laravel MongoDB package, please update: 
- Name: mongodb/laravel-mongodb
- URL: https://github.com/mongodb/laravel-mongodb

Current:
<img width="591" alt="Screenshot 2024-04-25 at 7 35 19 AM" src="https://github.com/HassanZahirnia/laravel-package-ocean/assets/108942387/588f47ad-7eeb-411b-a42c-dc6c6f012d99">

**Comment by HassanZahirnia** [comment]
Thank you very much for reporting this! Fixed now ✅😊

**Comment by bisht2050** [comment]
Thanks for the quickfix!
